# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 16:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('criteria', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CheckInListItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CheckInListResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(max_length=100)),
                ('inOrOut', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='CheckInOrOutList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('inOrOut', models.CharField(max_length=3)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='CheckInOrOutListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTimeOut', models.DateTimeField()),
                ('expectedDateTimeIn', models.DateTimeField()),
                ('signatureFormFile', models.CharField(max_length=400)),
                ('checkedInBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checked_in_by_person', to=settings.AUTH_USER_MODEL)),
                ('checkedOutBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checked_out_by_person', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('manufacturer', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=200)),
                ('serial', models.CharField(max_length=200)),
                ('tag', models.CharField(max_length=200)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=200)),
                ('generalAccessRule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.AccessRule')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryDescription', models.CharField(max_length=500)),
                ('categoryName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ItemState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ItemStateLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTimeChanged', models.DateTimeField()),
                ('changedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Item')),
                ('itemState', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.ItemState')),
            ],
        ),
        migrations.CreateModel(
            name='ItemSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subCategoryName', models.CharField(max_length=100)),
                ('subCategoryDescription', models.CharField(max_length=500)),
                ('itemCategoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.ItemCategory')),
                ('parentSubCategoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.ItemSubCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('requester', models.CharField(max_length=100)),
                ('isApproved', models.BooleanField(max_length=200)),
                ('major', models.CharField(max_length=50)),
                ('lengthOfCheckout', models.DurationField()),
                ('quantity', models.IntegerField()),
                ('itemCategoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.ItemCategory')),
                ('itemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Item')),
                ('itemSubCategoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.ItemSubCategory')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Reservation')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResponseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='itemState',
            field=models.ManyToManyField(through='backend.ItemStateLog', to='backend.ItemState'),
        ),
        migrations.AddField(
            model_name='item',
            name='subCategoryID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.ItemSubCategory'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='itemID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Item'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkedout_to_person', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checkinoroutlistitem',
            name='responseTypeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.ResponseType'),
        ),
        migrations.AddField(
            model_name='checkinoroutlist',
            name='checkInListItems',
            field=models.ManyToManyField(through='backend.CheckInListItems', to='backend.CheckInOrOutListItem'),
        ),
        migrations.AddField(
            model_name='checkinoroutlist',
            name='itemCategoryID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.ItemCategory'),
        ),
        migrations.AddField(
            model_name='checkinoroutlist',
            name='itemID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Item'),
        ),
        migrations.AddField(
            model_name='checkinoroutlist',
            name='itemSubCategoryID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.ItemSubCategory'),
        ),
        migrations.AddField(
            model_name='checkinlistresults',
            name='checkInOrOutListItem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.CheckInOrOutListItem'),
        ),
        migrations.AddField(
            model_name='checkinlistresults',
            name='checkout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Checkout'),
        ),
        migrations.AddField(
            model_name='checkinlistitems',
            name='checkInOrOutList',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.CheckInOrOutList'),
        ),
        migrations.AddField(
            model_name='checkinlistitems',
            name='checkInOrOutListItem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.CheckInOrOutListItem'),
        ),
        migrations.AlterUniqueTogether(
            name='reservationuser',
            unique_together=set([('userID', 'reservationID')]),
        ),
    ]
