# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20170326_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationrequest',
            name='classRequestedFor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
