# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 00:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20170221_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='checkedInBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checked_in_by_person', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='checkedOutBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checked_out_by_person', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='dateTimeOut',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkedout_to_person', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='signatureFormFile',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
