# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 15:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0004_remove_reservationrequest_itemcategoryid'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationrequest',
            name='declinedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='declined_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservationrequest',
            name='declinedOn',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='reservationrequest',
            name='declinedReason',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
