# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20170224_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutitem',
            name='dateTimeDue',
            field=models.DateTimeField(null=True),
        ),
    ]
