# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20170331_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='itemState',
            field=models.ManyToManyField(through='backend.ItemStateLog', to='backend.ItemState'),
        ),
    ]
