# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20170224_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='defaultCheckoutLengthDays',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='itemsubcategory',
            name='defaultCheckoutLengthDays',
            field=models.IntegerField(null=True),
        ),
    ]
