# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20170226_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsubcategory',
            name='parentSubCategoryID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.ItemSubCategory'),
        ),
    ]
