# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20170226_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutitem',
            name='dueDateOverridden',
            field=models.BooleanField(default=False),
        ),
    ]
