# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-27 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_itemtype_needssignature'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='needsSignature',
            field=models.BooleanField(default=False),
        ),
    ]
