# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_checkout_needssignature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='signatureFormFile',
            field=models.FileField(max_length=400, null=True, upload_to='uploads/signatures'),
        ),
    ]
