# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_checkoutitem_duedateoverridden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='checkoutStatus',
            field=models.CharField(default='Checked in', max_length=50),
        ),
    ]
