# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20170226_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutitem',
            name='dateTimeIn',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
