# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-03 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20170501_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='barcode',
            field=models.CharField(default=123456789, max_length=200),
            preserve_default=False,
        ),
    ]
