# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-03 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_item_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='barcode',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
