# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 00:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0010_auto_20170302_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='checkedInBy',
        ),
        migrations.AddField(
            model_name='checkoutitem',
            name='checkedInBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checked_in_by_person', to=settings.AUTH_USER_MODEL),
        ),
    ]
