# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-04 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20170503_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtype',
            name='defaultCheckoutLengthDays',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
