# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20170303_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.FileField(null=True, upload_to='uploads/itemImages'),
        ),
    ]
