# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-05 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20170504_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsubcategory',
            name='defaultCheckoutLengthDays',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
